### ISSUE TITLE
licensing question

### ISSUE THREAD

**Issue by jaymecd** [awslabs/cloudformation-validation-pipeline#4]
hi @hyandell , @shsenior ,
like this solution and amount of work you've done to write all that functionality.

I'd like to integrate some of these libraries/files (with partial modifications) into solutions I create for my customers.

Since this repository is covered under `Amazon Software License`, a non open-source licence, I have clarify first:

- am I allowed to use it within my solutions?
- am I allowed to modify it?
- what else I should worry before using it?

Thank you in advance.

**Comment by vijaysat1** [comment]
Hi,
    The solution is available for customization and usage according to your requirements.
am I allowed to use it within my solutions?
- Yes, the solution can be customized as per your needs.
am I allowed to modify it?
- Yes, you can modify it and use it for your custom needs and can raise a pull request for any valued feature enhancements that you can contribute.
what else I should worry before using it?
- None
 
Thank you
